hash-format = "sha256"

[[files]]
file = "mods/distanthorizons.pw.toml"
hash = "a43e3d76464a16015d62ba08d51da734f92377f0889c3984656d6d5739d284b2"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "cbda4f1881cfb9f054395a3db225df4202d1f2e7bd0ed27d803b837fcf728621"
metafile = true

[[files]]
file = "mods/fabricproxy-lite.pw.toml"
hash = "7345effda3ffcc376275666335af5b8a504887d1e95d13b257cb7e44695ba1aa"
metafile = true

[[files]]
file = "mods/geyser.pw.toml"
hash = "942002a0035d397b02e7a959944ccff8e2a57c9c9fc55db2339c7768995ae7aa"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "cdde1ed66709cde0656be902a1109532f255fd1526991acebe91116a4ab399df"
metafile = true
