hash-format = "sha256"

[[files]]
file = "mods/distanthorizons.pw.toml"
hash = "a43e3d76464a16015d62ba08d51da734f92377f0889c3984656d6d5739d284b2"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "b51659a7fdd17e134028a747bd8e4e8fb9ab9d88038577d088049a5c381f09dc"
metafile = true

[[files]]
file = "mods/fabricproxy-lite.pw.toml"
hash = "7345effda3ffcc376275666335af5b8a504887d1e95d13b257cb7e44695ba1aa"
metafile = true

[[files]]
file = "mods/geyser.pw.toml"
hash = "1ea81e3584c8dbdac95964ca43aa2e5b0076b6534ae4a2ae077e4b8581f5e3f3"
metafile = true
