name = "Vanilla Server 1 21 X"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "793d2ab4c1fcbbab68d25a9bc303dd6d2a75c84bc3e91f7d284358f789e62f1b"

[versions]
fabric = "0.18.3"
minecraft = "1.21.11"
