name = "Vanilla Server 1 21 X"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1543a427623e4c2b6749d877c76ae7ae4e857c0e0324e43ec531e9fa30781c29"

[versions]
fabric = "0.18.3"
minecraft = "1.21.11"
