name = "Vanilla Server 1 21 X"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8c74558bb0cf7154515406e853828016de776cbdd7e12d5e29f42c25c80727d6"

[versions]
fabric = "0.17.3"
minecraft = "1.21.10"
