name = "Vanilla Server 1 21 X"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "10caf3a8c2c80529e0be7ca0e0e2056647fd90a191cb272327dd9ea49fccfa7e"

[versions]
fabric = "0.17.3"
minecraft = "1.21.10"
