name = "Vanilla Server 1 21 X"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7380e271277736bd7eaeacec284e95bdd6fb8d9f7d4ecfaa1ba392916f069a3e"

[versions]
fabric = "0.17.3"
minecraft = "1.21.11"
