hash-format = "sha256"

[[files]]
file = "README.md"
hash = "553c497eb995835c769801a44772786079a0606df5de7e83cb2da5151cab220d"

[[files]]
file = "config/DistantHorizons.toml"
hash = "21288e22d411e1f7c9dc298605c28b55014b0360745c0c3f796a3d4b16cca065"

[[files]]
file = "config/almostunified/duplicates.json"
hash = "2d170752df03e26ce7d92e5aee18a2a9792c56c00bb8e2e6581ef9090f14529c"

[[files]]
file = "config/almostunified/placeholders.json"
hash = "43733b207b9f0238c7a5bec47f19e8fd5bec80499b286e0ac4994671702dfed9"

[[files]]
file = "config/almostunified/startup.json"
hash = "37f013c49586db025c17f9fa6657c6f239e0169ebc97ef682ff114a2ede43c5e"

[[files]]
file = "config/almostunified/tags.json"
hash = "699a55ef3879a9091caa49e0f7ec69fa7fc8f97eb96744ba51c634c3f2d62fd8"

[[files]]
file = "config/almostunified/unification/materials.json"
hash = "30dfa4d57b1a6895cdf8e889080a870d1766e54e16167b09c36d1ce0e4423c73"

[[files]]
file = "config/colorwheel-client.toml"
hash = "3cb43d65a1c4aa8a62fc1bf76661c065f9e886e44932ed584a5dffe97fb2e67b"

[[files]]
file = "config/copycats-common.toml"
hash = "9a44db2845c385061df03036470ed122b186ae0d5dd9925146470faf24ade2a9"

[[files]]
file = "config/create-server.toml"
hash = "7ba3ff9f2e51c045bf49828ca4e9fd3b181323e8278ebe6417d274fee1164254"

[[files]]
file = "config/item_obliterator.json5"
hash = "939aa767a753e3b61334a1d519d7d33fce0d6e9e4ab1cfcf075169093410d63f"

[[files]]
file = "config/naturaltemperature-common.toml"
hash = "fbd539ecdb773d6301920692b3f798b1d43722e431f53d48fce08224c632a40d"

[[files]]
file = "config/particlerain.json"
hash = "f903a8a6c5b8611eada8baf184bd478b6d4b8debb97c7fee72fd7b46c8259f22"

[[files]]
file = "config/paxi/datapacks/compat/data/dam/recipes/compacting/printed_silicon.json"
hash = "3b8380380e7a3f9f5d1306c0d603d564a8bddc4c801feacbe4f5832c92847371"

[[files]]
file = "config/paxi/datapacks/compat/pack.mcmeta"
hash = "fdfddef7add3e4d5da185c9118e0542a578f0931db465131f89c25d4cfbf0e65"

[[files]]
file = "config/paxi/datapacks/dam_no_ae2_meteorite/data/ae2/tags/worldgen/biome/has_structure/meteorites.json"
hash = "bcfce339f99bee08e4045ebf950d44cd24d22698a23eee5b231fe2eb320a8794"

[[files]]
file = "config/paxi/datapacks/dam_no_ae2_meteorite/pack.mcmeta"
hash = "4d06be22299bc6547cb19df35c8f3561d732da46d7e67b4a42c55cca52ebb0e3"

[[files]]
file = "config/paxi/resourcepacks/better-leaves.pw.toml"
hash = "f23b343e4a4555895e697c5ce98971809056a721e4732e25ea5b6952d91c0180"
metafile = true

[[files]]
file = "config/paxi/resourcepacks/fancy-crops.pw.toml"
hash = "b843c282f94af79a4970c91879eff4073932409aa045b722b48054bd4b2fd45d"
metafile = true

[[files]]
file = "config/paxi/resourcepacks/refined-storage-recreated.pw.toml"
hash = "fa48e21477d4eee6f28644ca57f280ff8f0d9ad1bf45fbdcd29e73a5895e4c30"
metafile = true

[[files]]
file = "config/tectonic.json"
hash = "eb60056a979c07b0c66abc02d13c03d48969eac7da14ff71d22f2aa904d07459"

[[files]]
file = "config/waterframes-server.toml"
hash = "3246b602321836a598657ba04a686d7c62bfc2dcb73a76bfab0e131317e0b9b5"

[[files]]
file = "kubejs/assets/dam/textures/item/cpu.png"
hash = "1f4d0584a282e42397ab922bbca47cb0343a0359899cbb19375f3fffb850d58a"

[[files]]
file = "kubejs/assets/dam/textures/item/defective_wafer.png"
hash = "fc299c3a839529329e7774061c6658426118b269f136da4a463a41ae067f117d"

[[files]]
file = "kubejs/assets/dam/textures/item/incomplete_silicon_wafer.png"
hash = "085b1680210fe78cb428c44ef003c8d99aebab4969b5229929c05d980af2b332"

[[files]]
file = "kubejs/assets/dam/textures/item/microprocessor.png"
hash = "dd9f32abd16eeffa5670c1cbaa470fd6c6e0c8baac5a491e006cceeeef148101"

[[files]]
file = "kubejs/assets/dam/textures/item/patterned_wafer.png"
hash = "142e566f253588c52911de9be946727b4f00b491961a99ad0cabc90ebc153d54"

[[files]]
file = "kubejs/assets/dam/textures/item/processor.png"
hash = "922f5edce374a45cdf4b3f09b9d5e48cd9fdb8fa03c2b47d190df66f15b23e4c"

[[files]]
file = "kubejs/assets/dam/textures/item/processor_package.png"
hash = "6c5e34fce3c9e25ce23fabe88856ec35423cf37265f8f282100f466ec19f49fe"

[[files]]
file = "kubejs/assets/dam/textures/item/raw_silicon_wafer.png"
hash = "f04476068755614e8c8d592d2d2227afceb6e45d36f3050242b6b78c68b5e4be"

[[files]]
file = "kubejs/assets/dam/textures/item/silicon_die.png"
hash = "315cd56ae95a94ec45b9833281cc4057e32bbc73af6f4c252d772bd57190b940"

[[files]]
file = "kubejs/assets/dam/textures/item/silicon_wafer.png"
hash = "c9b3591fcc6a246ed9284cbfe542f60631870594240f8f1ccb84513aa2f956f5"

[[files]]
file = "kubejs/client_scripts/via.js"
hash = "23dd7aee293a82571892ce78b84795ff849b14561d72587624bd53e91f578ced"

[[files]]
file = "kubejs/server_scripts/ae2.js"
hash = "a4a34f3f2a9d6ba6d29c64389a569373ac57b3713b48b999f50832d67f006f73"

[[files]]
file = "kubejs/server_scripts/refined_storage.js"
hash = "565f388f5b2a4e11f0f8f66fae279d24bdd585cecd4aecd4b8db8445a36dc840"

[[files]]
file = "kubejs/server_scripts/wafer.js"
hash = "715b1cecf2b94bbc5b5aae2d5a7012691a8ffc0b48405d1f6ca151cc02d7a98c"

[[files]]
file = "kubejs/startup_scripts/wafer.js"
hash = "584778e746db6a7ea0f9f2ebfe48fb4aa027726d99c966f34ac2a7aad2e51a75"

[[files]]
file = "mods/colorwheel.pw.toml"
hash = "934d5afe2c8d68e991a5e24955c35abde9511a466ab62b34485363ad3f4dc43b"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "65c8086d2ec3d39acc7bd36c7a0306ccc43b602b38fa07d13291bc478ef7dfff"
metafile = true

[[files]]
file = "mods/create-compatible-storage.pw.toml"
hash = "c1015581ea9139b9955a3042f69e092926e4cfe2a5d7f426267219b947f9f4f2"
metafile = true

[[files]]
file = "mods/create-connected.pw.toml"
hash = "a10ca44e38b499dd749e8522b51f16815ddbb60483806a58b0845f179b6b8440"
metafile = true

[[files]]
file = "mods/create-new-age.pw.toml"
hash = "637a0f8e81eebbb776d07f7ce32d6b67675000b6259beacec1cbb1b1d730683d"
metafile = true

[[files]]
file = "mods/create-pattern-schematics.pw.toml"
hash = "faddfa6807d11014c93bbfd8e543e8843e6d44e53f70d54e0b7e3e95766d2021"
metafile = true

[[files]]
file = "mods/create-power-loader.pw.toml"
hash = "ee76dbe108ebf5cf68047f60ecabee5aeb029015253dc82c007b941a6d6cfcdf"
metafile = true

[[files]]
file = "mods/create-tfmg.pw.toml"
hash = "e9561ff24c431e4fd95d851f4d9755b52b52a5c24ecc3a1ad15ab8ef20087ba9"
metafile = true

[[files]]
file = "mods/create.pw.toml"
hash = "d6043c928c34ce1f4ada544a49193f95c281665cf88d4931e73370ea02870bed"
metafile = true

[[files]]
file = "mods/creativecore.pw.toml"
hash = "48cbc3da595efc9c3e04fb06bf9ba71861fcbd2e70dc1596a38ccb14b5179edc"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
hash = "d3c9b48d7caa2ed964e5d1a4dab1da5655c63f0a7e4a59231c4369be7ffc30e1"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "f67aa60c765593a8c70f78296a460349c6aef5f4a16d173eae02e8803b545ad4"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "6bc414cc0f2d4c078fe83f384d786343f701f371d657c5279b5b0df1595804bd"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "ce9ddada6ffd55a512149cc474c6a453281a997a5fdf1b7b4a2cc73f875e704a"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "82fa5e74cae0b3f0199f9822f62a976da2dc6ee03deb543d537ce55d36b11fcb"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "0281ed9713f3141bdac363056a791845510e14761ea65b4b2813cf96d664b20a"
metafile = true

[[files]]
file = "mods/sound-physics-perfected.pw.toml"
hash = "bb2880163c874a52f90f0abe23c22ac3ed27ef867254e6de6ec5c65360355860"
metafile = true

[[files]]
file = "mods/waterframes.pw.toml"
hash = "a255c29cb611f60aaad313b223bc424721be5998673002da6b589b2862912621"
metafile = true

[[files]]
file = "mods/watermedia.pw.toml"
hash = "f92f076e36b732f61db1a8553d73758be63e5841d26f229dd20a7d33b973f22f"
metafile = true

[[files]]
file = "mods/watervision.pw.toml"
hash = "393310e8c75c51eb3143c8ddcdac51917a5d759d428e5b962e4c2b4c8e87bc0e"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "64eaf7478e42d5143f4feeee87c56f779f4c3523f9fb06d8342484d36aa4442b"
metafile = true

[[files]]
file = "shaderpacks/bsl-shaders.pw.toml"
hash = "d30923bf5cfb4988a372508cb461d8077609d79a38d0b170785804c7ad15f16e"
metafile = true

[[files]]
file = "shaderpacks/complementary-reimagined.pw.toml"
hash = "531a8d239c952428d9a633ff99cb03461656ada28decbe2e1ef19f60f7fd5726"
metafile = true

[[files]]
file = "shaderpacks/rethinking-voxels.pw.toml"
hash = "0a3f01f56afd065dc65dffb073b4fc5f9ae031aaef08d95d9df92e0093ac8504"
metafile = true
