hash-format = "sha256"

[[files]]
file = "README.md"
hash = "553c497eb995835c769801a44772786079a0606df5de7e83cb2da5151cab220d"

[[files]]
file = "config/DistantHorizons.toml"
hash = "21288e22d411e1f7c9dc298605c28b55014b0360745c0c3f796a3d4b16cca065"

[[files]]
file = "config/almostunified/debug.json"
hash = "435ad46870d033c8652097d64c6ec592907e5ab6f1877240532a6a1743d4fca5"

[[files]]
file = "config/almostunified/duplicates.json"
hash = "2d170752df03e26ce7d92e5aee18a2a9792c56c00bb8e2e6581ef9090f14529c"

[[files]]
file = "config/almostunified/placeholders.json"
hash = "43733b207b9f0238c7a5bec47f19e8fd5bec80499b286e0ac4994671702dfed9"

[[files]]
file = "config/almostunified/startup.json"
hash = "37f013c49586db025c17f9fa6657c6f239e0169ebc97ef682ff114a2ede43c5e"

[[files]]
file = "config/almostunified/tags.json"
hash = "699a55ef3879a9091caa49e0f7ec69fa7fc8f97eb96744ba51c634c3f2d62fd8"

[[files]]
file = "config/almostunified/unification/materials.json"
hash = "30dfa4d57b1a6895cdf8e889080a870d1766e54e16167b09c36d1ce0e4423c73"

[[files]]
file = "config/astikorcartsredux-common.toml"
hash = "cc6bf6cd24f542fbcd8c1ec8a72b87df72c353be58599e89b77f0d07bc8096c6"

[[files]]
file = "config/colorwheel-client.toml"
hash = "3cb43d65a1c4aa8a62fc1bf76661c065f9e886e44932ed584a5dffe97fb2e67b"

[[files]]
file = "config/copycats-common.toml"
hash = "9a44db2845c385061df03036470ed122b186ae0d5dd9925146470faf24ade2a9"

[[files]]
file = "config/create-server.toml"
hash = "7ba3ff9f2e51c045bf49828ca4e9fd3b181323e8278ebe6417d274fee1164254"

[[files]]
file = "config/item_obliterator.json5"
hash = "939aa767a753e3b61334a1d519d7d33fce0d6e9e4ab1cfcf075169093410d63f"

[[files]]
file = "config/naturaltemperature-common.toml"
hash = "fbd539ecdb773d6301920692b3f798b1d43722e431f53d48fce08224c632a40d"

[[files]]
file = "config/particlerain.json"
hash = "f903a8a6c5b8611eada8baf184bd478b6d4b8debb97c7fee72fd7b46c8259f22"

[[files]]
file = "config/paxi/datapacks/compat/data/dam/recipes/compacting/printed_silicon.json"
hash = "3b8380380e7a3f9f5d1306c0d603d564a8bddc4c801feacbe4f5832c92847371"

[[files]]
file = "config/paxi/datapacks/compat/pack.mcmeta"
hash = "fdfddef7add3e4d5da185c9118e0542a578f0931db465131f89c25d4cfbf0e65"

[[files]]
file = "config/paxi/datapacks/dam_no_ae2_meteorite/data/ae2/tags/worldgen/biome/has_structure/meteorites.json"
hash = "bcfce339f99bee08e4045ebf950d44cd24d22698a23eee5b231fe2eb320a8794"

[[files]]
file = "config/paxi/datapacks/dam_no_ae2_meteorite/pack.mcmeta"
hash = "4d06be22299bc6547cb19df35c8f3561d732da46d7e67b4a42c55cca52ebb0e3"

[[files]]
file = "config/paxi/resourcepacks/better-leaves.pw.toml"
hash = "f23b343e4a4555895e697c5ce98971809056a721e4732e25ea5b6952d91c0180"
metafile = true

[[files]]
file = "config/paxi/resourcepacks/fancy-crops.pw.toml"
hash = "b843c282f94af79a4970c91879eff4073932409aa045b722b48054bd4b2fd45d"
metafile = true

[[files]]
file = "config/paxi/resourcepacks/refined-storage-recreated.pw.toml"
hash = "fa48e21477d4eee6f28644ca57f280ff8f0d9ad1bf45fbdcd29e73a5895e4c30"
metafile = true

[[files]]
file = "config/sparsestructures.json5"
hash = "fd0cc205947abfc66bbf3e04163f371c62603ea252390e766e7434fd83d9ee99"

[[files]]
file = "config/tectonic.json"
hash = "536b77893cb8908d814c5ab48ef4538eae2c654c7e5c94fd31a9a58c942224d5"

[[files]]
file = "config/treechop-common.toml"
hash = "357ecb1b69f83f1ef1534d5debd1aaf909f28583774af14340c5992dbed97f82"

[[files]]
file = "config/waterframes-server.toml"
hash = "3246b602321836a598657ba04a686d7c62bfc2dcb73a76bfab0e131317e0b9b5"

[[files]]
file = "kubejs/assets/dam/textures/item/circuit_board.png"
hash = "2770fc8528d1daab114e5c66c27432db1c43dc45606df63ccf0814c3cbc68ac8"

[[files]]
file = "kubejs/assets/dam/textures/item/cpu.png"
hash = "1f4d0584a282e42397ab922bbca47cb0343a0359899cbb19375f3fffb850d58a"

[[files]]
file = "kubejs/assets/dam/textures/item/incomplete_silicon_wafer.png"
hash = "085b1680210fe78cb428c44ef003c8d99aebab4969b5229929c05d980af2b332"

[[files]]
file = "kubejs/assets/dam/textures/item/microprocessor.png"
hash = "dd9f32abd16eeffa5670c1cbaa470fd6c6e0c8baac5a491e006cceeeef148101"

[[files]]
file = "kubejs/assets/dam/textures/item/n_semiconductor.png"
hash = "ab76230f7a22611786159e5172886e07031bc911b89818d564667c8c49e18ab5"

[[files]]
file = "kubejs/assets/dam/textures/item/p_semiconductor.png"
hash = "b9529d7de5223cdeea0eab3460337092fbfff0fcd7c16b5bcca57baa8ce79b79"

[[files]]
file = "kubejs/assets/dam/textures/item/processor.png"
hash = "922f5edce374a45cdf4b3f09b9d5e48cd9fdb8fa03c2b47d190df66f15b23e4c"

[[files]]
file = "kubejs/assets/dam/textures/item/processor_package.png"
hash = "6c5e34fce3c9e25ce23fabe88856ec35423cf37265f8f282100f466ec19f49fe"

[[files]]
file = "kubejs/assets/dam/textures/item/raw_silicon_wafer.png"
hash = "f04476068755614e8c8d592d2d2227afceb6e45d36f3050242b6b78c68b5e4be"

[[files]]
file = "kubejs/assets/dam/textures/item/resistor.png"
hash = "42315395360aa6f1c9a88f47171bfe1480f90ae2e0ba0e34be5de929cdad2f58"

[[files]]
file = "kubejs/assets/dam/textures/item/silicon_die.png"
hash = "315cd56ae95a94ec45b9833281cc4057e32bbc73af6f4c252d772bd57190b940"

[[files]]
file = "kubejs/assets/dam/textures/item/silicon_wafer.png"
hash = "c9b3591fcc6a246ed9284cbfe542f60631870594240f8f1ccb84513aa2f956f5"

[[files]]
file = "kubejs/assets/dam/textures/item/transistor.png"
hash = "81c9e3f237002b2c6a1c2bec386e11665923e58253f008b2525c725e7fa8f907"

[[files]]
file = "kubejs/assets/dam/textures/item/transistor_item.png"
hash = "e0c6a1875ed979c341ba663612f83d28c75a380a9cd82f7898d12333b1e93052"

[[files]]
file = "kubejs/assets/dam/textures/item/unfinished_resistor.png"
hash = "cc07bd102cb4121756ce6d3e4781fd8fcd0da37be75b7e8d2859182ad41c27be"

[[files]]
file = "kubejs/assets/kubejs/lang/en_us.json"
hash = "469f774a06198beac18b384210efde463e513d4b68760df626bc992d64e9f9e2"

[[files]]
file = "kubejs/client_scripts/guideline.md"
hash = "476faf42b5aeb3c7e0f4aab2e26e2f4794169152e37c08876169ecbe5fa57ce7"

[[files]]
file = "kubejs/client_scripts/via.js"
hash = "23dd7aee293a82571892ce78b84795ff849b14561d72587624bd53e91f578ced"

[[files]]
file = "kubejs/server_scripts/ae2.jsoff"
hash = "a4a34f3f2a9d6ba6d29c64389a569373ac57b3713b48b999f50832d67f006f73"

[[files]]
file = "kubejs/server_scripts/refined_storage.jsoff"
hash = "565f388f5b2a4e11f0f8f66fae279d24bdd585cecd4aecd4b8db8445a36dc840"

[[files]]
file = "kubejs/server_scripts/semiconductors.js"
hash = "b668a3bb2615f4759954643408171acef57f4abe6187d12d33c851cf86f7d219"

[[files]]
file = "kubejs/server_scripts/wafer.js"
hash = "7687f0da7137647d5283a6be6218a71265c6595a9b28d1270de70bc9422a90e9"

[[files]]
file = "kubejs/server_scripts/wafer.jsoff"
hash = "7687f0da7137647d5283a6be6218a71265c6595a9b28d1270de70bc9422a90e9"

[[files]]
file = "kubejs/startup_scripts/wafer.js"
hash = "a7a70aabbba1e8b32638fe6197add7b8ec1a7a5cae66c369f74c8537aed6a3f0"

[[files]]
file = "mods/accessories-cc-layer.pw.toml"
hash = "8f90a500df28d497fe7e323b40ee55640bc63141284ce2189a7766c976a91378"
metafile = true

[[files]]
file = "mods/accessories.pw.toml"
hash = "5b786ab7a57e37ec4b8f888157f79608e871653fc4b6a8cba0296690fe863704"
metafile = true

[[files]]
file = "mods/ae2.pw.toml"
hash = "ed45c352a49b65c7221e57d979d0c6935522dfef4968aa5b7421f4d3e670ce40"
metafile = true

[[files]]
file = "mods/almost-unified.pw.toml"
hash = "cd3dc0764b530a3323e94b880f9ee9f1910036468245dcfb32c4702e19494b0f"
metafile = true

[[files]]
file = "mods/astikorcarts-redux.pw.toml"
hash = "ae56960397cf0e01f21b448093590643ad70bb390da44732ca46dc5261f4d536"
metafile = true

[[files]]
file = "mods/autohud.pw.toml"
hash = "1d39c4b2c4554ef1532b3f0d22e6a06d8750ce11acb2f51ba7d78868c7f4cdb7"
metafile = true

[[files]]
file = "mods/betterdays.pw.toml"
hash = "491bbce364b6fefc3ec6292cde7c2cd17b18f358f2bf59628c9d84ba9c43d2f6"
metafile = true

[[files]]
file = "mods/carry-on.pw.toml"
hash = "8fde54624913d86f1176cd1086fa485f1a872573dac144347c57cab76596b715"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "75181b55e0407d1fca1e2f346c6501f919f5109545990ddfb66db9cd1b771f8a"
metafile = true

[[files]]
file = "mods/colorwheel-patcher.pw.toml"
hash = "44f9462f2bdb7f3254ef7d7639271159b8b2dd0deffb902d5425e883a38b35ca"
metafile = true

[[files]]
file = "mods/colorwheel.pw.toml"
hash = "934d5afe2c8d68e991a5e24955c35abde9511a466ab62b34485363ad3f4dc43b"
metafile = true

[[files]]
file = "mods/common-network.pw.toml"
hash = "cd8078f4d044e9fb548c2b792f2f1f1c04e1b80e1479446f67de3e8687dfbf67"
metafile = true

[[files]]
file = "mods/configurable.pw.toml"
hash = "40c591457bd4a745782bb1005f9446ef9b2f4bb2e5a56b00fd216c0ee57a3570"
metafile = true

[[files]]
file = "mods/connector-extras.pw.toml"
hash = "52e2cb54ee2933bf00e9b7886f47938a2dce1bf998293be2b38552083ffa5f9a"
metafile = true

[[files]]
file = "mods/connector.pw.toml"
hash = "c27af69a7c64206beff3e59c671934d4eb9a3dc65fd589609c5e6f6bb60421bb"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "65c8086d2ec3d39acc7bd36c7a0306ccc43b602b38fa07d13291bc478ef7dfff"
metafile = true

[[files]]
file = "mods/copycats.pw.toml"
hash = "bf463928645c586cb57a4e02533ee300af3931cf9db9233dae7efc1826643d41"
metafile = true

[[files]]
file = "mods/corgilib.pw.toml"
hash = "7cd10de618c7f46c1877d9d3e597699a7fcc02cf3982bba439ccbec95a37d0de"
metafile = true

[[files]]
file = "mods/create-connected.pw.toml"
hash = "aea6d37ae312cafb92d9456c9b16e7e8406ba03c5dab5c4ade19a204c509ec85"
metafile = true

[[files]]
file = "mods/create-new-age.pw.toml"
hash = "637a0f8e81eebbb776d07f7ce32d6b67675000b6259beacec1cbb1b1d730683d"
metafile = true

[[files]]
file = "mods/create-power-loader.pw.toml"
hash = "ee76dbe108ebf5cf68047f60ecabee5aeb029015253dc82c007b941a6d6cfcdf"
metafile = true

[[files]]
file = "mods/create-tfmg.pw.toml"
hash = "e9561ff24c431e4fd95d851f4d9755b52b52a5c24ecc3a1ad15ab8ef20087ba9"
metafile = true

[[files]]
file = "mods/create.pw.toml"
hash = "d6043c928c34ce1f4ada544a49193f95c281665cf88d4931e73370ea02870bed"
metafile = true

[[files]]
file = "mods/creativecore.pw.toml"
hash = "48cbc3da595efc9c3e04fb06bf9ba71861fcbd2e70dc1596a38ccb14b5179edc"
metafile = true

[[files]]
file = "mods/data-anchor.pw.toml"
hash = "7b7a61e6724eab42b13f406d235c9665e69425a182283dbba35fdd7bdfbd8745"
metafile = true

[[files]]
file = "mods/distanthorizons.pw.toml"
hash = "3f8fb0012b658c3ed2dfcde1385aa6255ee46cd18b77975d68665aaf0ee2a94d"
metafile = true

[[files]]
file = "mods/emi-enchanting.pw.toml"
hash = "ff029ee6fc50f2696e96cdbcc696f42e75b483c9d7b83f2b1447dcf5c865e664"
metafile = true

[[files]]
file = "mods/emi-loot.pw.toml"
hash = "bbf03bec2bd4927ace16eef106c45b0f3ec53c48d5f43119520123ad98f3fdf1"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
hash = "d3c9b48d7caa2ed964e5d1a4dab1da5655c63f0a7e4a59231c4369be7ffc30e1"
metafile = true

[[files]]
file = "mods/endrem.pw.toml"
hash = "db22718a1efaf2c691cf3bdddc61b0b06bedff7cb0722aa8b1bdf4f095d116cc"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "dfc5252f31339a2f2b900399802f2e787ebe4d6e061bd150aaef50a20d2a6d20"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "847b1ef4cab7e5310e058ec2118f4e257327252c230bea328afacac3b1ddd9ad"
metafile = true

[[files]]
file = "mods/euphoria-patches.pw.toml"
hash = "cd77d7f479a925f2c5147a9e4103a7c35c19292bf3a3144a59ecbb2905ceba62"
metafile = true

[[files]]
file = "mods/every-compat.pw.toml"
hash = "ce8ed8b130007ccc3d3e27d4e278baade5614bfd9b73f6d5ab0be66ceea159e3"
metafile = true

[[files]]
file = "mods/fdlib.pw.toml"
hash = "5293ee5ce35baf07ce516a53d10f33230da8fc004ad2a443468b0dd3be85b06c"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "05d96d5b17399f048469ff4b44451eb8d99cc7a2a075ff55718c397cb508b0c2"
metafile = true

[[files]]
file = "mods/floral-enchantment.pw.toml"
hash = "ef46e8181dd304ebae9fc112600b3d87ecf457c4f4d48513587549ea57dd40bc"
metafile = true

[[files]]
file = "mods/flw-vanillin.pw.toml"
hash = "cbcaf4a18e45757f17d4a4f36469f879ae024a9fe58b8129d8a42d0faaeada22"
metafile = true

[[files]]
file = "mods/forgified-fabric-api.pw.toml"
hash = "ec1bd5b80399287ca33a113086bee9d5697b7e673c9f593e5a1aeca4c9bad4c9"
metafile = true

[[files]]
file = "mods/fzzy-config.pw.toml"
hash = "11c4ac6932c14f3ad5a2c63d7f39eee1e9a2a91ffc079d5bd917c9aa381abdfb"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "960fb33c17aca9c635f99009c1f16d75c312d043e302a599f6ce8040452079e6"
metafile = true

[[files]]
file = "mods/glitchcore.pw.toml"
hash = "dbd756dd9bb17e6ecebcf2d7052a67a2da1c7dd378bc2089bc154916080fe031"
metafile = true

[[files]]
file = "mods/guideme.pw.toml"
hash = "b8aee2057378b6f054f94550684d9a3f41ded7cc47794c8b01c107c8c2115ceb"
metafile = true

[[files]]
file = "mods/immersive-snow.pw.toml"
hash = "759ebd337fa67f558a204baef57041ca0392fd206c786a3e7643a5c6b27f4cee"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "f67aa60c765593a8c70f78296a460349c6aef5f4a16d173eae02e8803b545ad4"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "e7d3f7e0472ba9a3ef946fa5defcb157e4126636e603c2306d4ad6065936d5e2"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "543086dc0db330c268dcfcadaecd179ea389f0b5749d82ef6b06a22cfb7952e6"
metafile = true

[[files]]
file = "mods/kiwi.pw.toml"
hash = "caa948011054593b7452cfc4fa7276ff61748770285fd6b7ee5078816eed043b"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
hash = "1a9ec5beaba1be3151b8710db2bfab90c2063a4dafaf2720336852245a145cc4"
metafile = true

[[files]]
file = "mods/kubejs.pw.toml"
hash = "5113f78787651e11f104807a95760c4af97288c3602ca11d65205387a0886519"
metafile = true

[[files]]
file = "mods/larion-worldgen.pw.toml.inactive"
hash = "cfd9584cd85b80ce1bc993112f337200ea603149edb6bb47af5f5c915529adf4"

[[files]]
file = "mods/lithosphere.pw.toml.inactive"
hash = "337093b94742d334ad349d4fbfe1b74a9b885784ac6d43432896b3dc527260a9"

[[files]]
file = "mods/lithostitched.pw.toml"
hash = "f8edc1d5fadb1b65f8f869893ec637ec8a5e5f92fb0a7f140e9e62977668f895"
metafile = true

[[files]]
file = "mods/lukis-grand-capitals.pw.toml"
hash = "83a99ef96b53649cb77e37be095a4cc390e889580cf00ff13956646e43e4f2cb"
metafile = true

[[files]]
file = "mods/midnightlib.pw.toml"
hash = "7713cc82e1ea68848508ed5c1a1c7bd1a832c0bcc97c96865891b9a2a33aa825"
metafile = true

[[files]]
file = "mods/mmmmmmmmmmmm.pw.toml"
hash = "ad52f42cb5e9080cd493d1e7b2acfbc6c662ece8f094288604d54a224ce0e440"
metafile = true

[[files]]
file = "mods/moonlight.pw.toml"
hash = "34af73fbc06558118a046d6c4c26a555337f5e971ba59b42ca13471c57127f1f"
metafile = true

[[files]]
file = "mods/mowzies-mobs.pw.toml"
hash = "db3d3f1719c6f643a64565e3cf10c5cfe015deecd102e4059e37bf35dbda6364"
metafile = true

[[files]]
file = "mods/natural-temperature.pw.toml"
hash = "76a17ba4f1647b65aba18e87f9136b9f3f00178ee086dfc2a2be0c55032ef36c"
metafile = true

[[files]]
file = "mods/neruina.pw.toml"
hash = "bcc55af954d7ac052404ff4c8303566cb069223db99935e74ce6f9562db7f11b"
metafile = true

[[files]]
file = "mods/noisium.pw.toml"
hash = "d424a9260ef51bc102e56f0423d91dfabb739ccca8a86eb1c450ea631b739280"
metafile = true

[[files]]
file = "mods/oh-the-biomes-weve-gone.pw.toml.inactive"
hash = "ec36bc71d2ac55e7e596e88ceed31e0e1dafcc20fd55e4771aa12deb84a086f7"

[[files]]
file = "mods/oh-the-trees-youll-grow.pw.toml.inactive"
hash = "53e138a80512bf0cbf316a98a8b15f7736b8542f08325793057af67bd3df9961"

[[files]]
file = "mods/owo-lib.pw.toml"
hash = "46831c04077a06df823bcd0f254833a90a9a9ccc78f5069f4b4c27fa301ac0cf"
metafile = true

[[files]]
file = "mods/particle-rain.pw.toml"
hash = "95886f73121a490ab360dac8e99f260fb0346048e86475c658ed44ddd399f09e"
metafile = true

[[files]]
file = "mods/passable-foliage.pw.toml"
hash = "0260e1b1506d0ceece1d40014db6b6a36b1780fd6c8bd9f9fad23ae5fe0316f4"
metafile = true

[[files]]
file = "mods/paxi.pw.toml"
hash = "215d597764d5c5db89e700fc3495b72dc0a7f09c975de19dc8c580bde3469a5e"
metafile = true

[[files]]
file = "mods/ponder.pw.toml"
hash = "645655e6efa56ea48a5c0f84f5c745d3f0986c49497ce54f538318b1865138d3"
metafile = true

[[files]]
file = "mods/qliphoth-awakening.pw.toml"
hash = "688922712852e585a4d151c59e114afda341555f41f25f99a0d58fc6d7cae081"
metafile = true

[[files]]
file = "mods/refined-storage.pw.toml"
hash = "2615ce20109fe11c8673991a1eb2cdfea463cd38926c067a8b9088eee7a8607d"
metafile = true

[[files]]
file = "mods/rhino.pw.toml"
hash = "6b91f46291891e725189b0bd54d0db0f66925b1e785bdfa737592dfcf41a79a3"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "ce9ddada6ffd55a512149cc474c6a453281a997a5fdf1b7b4a2cc73f875e704a"
metafile = true

[[files]]
file = "mods/serene-seasons.pw.toml"
hash = "73b1e4f6608fcd396acc3e4e7aa753d314c8810ef4caf831ed93d9932d93f896"
metafile = true

[[files]]
file = "mods/snow-real-magic.pw.toml"
hash = "a1deef8071fb83a13df63c289576813b82f0687eebda9b48b7667620d5d45103"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "0281ed9713f3141bdac363056a791845510e14761ea65b4b2813cf96d664b20a"
metafile = true

[[files]]
file = "mods/sodiumleafculling.pw.toml"
hash = "a73dfb1bf6884ae786b2def0624dee9010bf121d0b5678b46043d9312f54b501"
metafile = true

[[files]]
file = "mods/sound-physics-perfected.pw.toml"
hash = "bb2880163c874a52f90f0abe23c22ac3ed27ef867254e6de6ec5c65360355860"
metafile = true

[[files]]
file = "mods/sparsestructures.pw.toml"
hash = "8c71edbbb86e5d3e1c14ea6629382539d44e75b1061725df9c3abceb889a8591"
metafile = true

[[files]]
file = "mods/tectonic.pw.toml"
hash = "8ad02530347f7b0dfe84b8eb081e2eaa23cae536de0d289137902f7557fb3a33"
metafile = true

[[files]]
file = "mods/terrablender.pw.toml"
hash = "15962183bec2468058c70e87aa32e902a08489b0f86741088cdc9aa958ba4931"
metafile = true

[[files]]
file = "mods/treechop.pw.toml"
hash = "da1c1cf28e8d5ffe377998d29d59eae29a2020f2de7a0aea7f7253acdc695cfd"
metafile = true

[[files]]
file = "mods/via-romana.pw.toml"
hash = "10094d35edff539271c05ce24570bb5fa73acd137207e5c699f021b864b698fd"
metafile = true

[[files]]
file = "mods/waterframes.pw.toml"
hash = "a255c29cb611f60aaad313b223bc424721be5998673002da6b589b2862912621"
metafile = true

[[files]]
file = "mods/watermedia.pw.toml"
hash = "f92f076e36b732f61db1a8553d73758be63e5841d26f229dd20a7d33b973f22f"
metafile = true

[[files]]
file = "mods/watervision.pw.toml"
hash = "393310e8c75c51eb3143c8ddcdac51917a5d759d428e5b962e4c2b4c8e87bc0e"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "64eaf7478e42d5143f4feeee87c56f779f4c3523f9fb06d8342484d36aa4442b"
metafile = true

[[files]]
file = "mods/yungs-api.pw.toml"
hash = "d9c0c9209bac0b693af2a7c1e47ffb28d366bad19c91df31dc6d345fa75250a1"
metafile = true

[[files]]
file = "shaderpacks/bsl-shaders.pw.toml"
hash = "d30923bf5cfb4988a372508cb461d8077609d79a38d0b170785804c7ad15f16e"
metafile = true

[[files]]
file = "shaderpacks/complementary-reimagined.pw.toml"
hash = "531a8d239c952428d9a633ff99cb03461656ada28decbe2e1ef19f60f7fd5726"
metafile = true

[[files]]
file = "shaderpacks/rethinking-voxels.pw.toml"
hash = "0a3f01f56afd065dc65dffb073b4fc5f9ae031aaef08d95d9df92e0093ac8504"
metafile = true
