name = "DAM (1.21)"
author = "Danny Le"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8ffd098515abe5a9f605a0ac7498deefeb7a27457d45d341fcd6e6f73ceffb79"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.214"

[options]
datapack-folder = "config/paxi/datapacks"
resource-folder = "config/paxi/resourcepacks"
