name = "DAM (1.21)"
author = "Danny Le"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "136e662bc09061f0f0a9c3279053dcf07dda59e172f8e521e1bb6636556dde45"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.214"

[options]
datapack-folder = "config/paxi/datapacks"
resource-folder = "config/paxi/resourcepacks"
