name = "DAM (1.21)"
author = "Danny Le"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "213bd9b5946f9fc9fe94c2644acaac56760066b39baedce27ab0b4a154e89590"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.214"

[options]
datapack-folder = "config/paxi/datapacks"
resource-folder = "config/paxi/resourcepacks"
