name = "DAM (1.21)"
author = "Danny Le"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fa525c8263daf8f24d8a4c1252d8d0ae177766b87ca594971c832fd4171f5da2"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.197"

[options]
datapack-folder = "config/paxi/datapacks"
resource-folder = "config/paxi/resourcepacks"
