name = "DAM (1.21)"
author = "Danny Le"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5b915a71b70fd8efc9e3d087a4be487394cccf3e31f03a02e35e5cdf392b1f36"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.214"

[options]
datapack-folder = "config/paxi/datapacks"
resource-folder = "config/paxi/resourcepacks"
